module.exports = {
    XPATH_BODY: "//body",
    XPATH_SUCCESS_ALERT: "//div[contains(text(),'successAlert')]",
    XPATH_ERROR_ALERT: "//div[contains(text(),'errorAlert')]",
    XPATH_ALERT_SHOW_INVISIBLE: "//div[contains(text(),'showInvisible()')]",
    XPATH_VISIBLE_SHOW_ALERT: "//div[@id='show-visible-alert']//div",
    XPATH_INVISIBLE_SHOW_ALERT: "//div[@id='show-invisible-alert']//div",
    XPATH_SHOW_BUTTON_ALERT: "//button[contains(text(),'Show Alert')]",
    XPATH_VISIBLE_HIDE_ALERT: "//div[@id='hide-visible-alert']//div",
    XPATH_INVISIBLE_HIDE_ALERT: "//div[@id='hide-invisible-alert']//div",
    XPATH_HIDE_BUTTON_ALERT: "//button[contains(text(), 'Hide Alert')]",
    // XPATH_ALERT_HIDE_VISIBLE: "//div[contains(text(),'hideVisible()')]",
    // XPATH_ALERT_HIDE_INVISIBLE: "//div[contains(text(),'hideInvisible()')]",
    // XPATH_ALERT_DISABLE_ENABLED: "//div[contains(text(),'disableEnabledAlert()')]",
    // XPATH_ALERT_ENABLE_DISABLED: "//div[contains(text(),'enableDisabledAlert()')]",
    XPATH_DISABLE_ENABLE_ALERT: "//div[@id='disable-enable-alert']//div",
    XPATH_DISABLE_DISABLE_ALERT: "//div[@id='disable-disable-alert']//div",
    XPATH_DISABLE_BUTTON_ALERT: "//button[contains(text(), 'Disable Alert')]",
    XPATH_ENABLE_ENABLE_ALERT: "//div[@id='enable-enable-alert']//div",
    XPATH_ENABLE_DISABLE_ALERT: "//div[@id='enable-disable-alert']//div",
    XPATH_ENABLE_BUTTON_ALERT: "//button[contains(text(), 'Enable Alert')]",
    XPATH_ALERT_ON_CALL_FUNCTION: "//div[contains(text(),'onCallbackFunctionAlert()')]",
    XPATH_ALERT_ON_TRIGGER_FUNCTION: "//div[contains(text(),'onCallbackTriggerAlert()')]",
    XPATH_FULL_OPTION_ALERT: "//div[@id='full-option-alert']//div",
    XPATH_SET_TEXT_ALERT: "//div[@id='set-text-alert']//div",
    XPATH_SET_TEXT_BUTTON_ALERT: "//button[contains(text(),'Set text for alert not contain existing text')]",
    XPATH_SET_TEXT_BUTTON_1_ALERT: "//button[contains(text(),'Set text for alert contain existing text')]",
    XPATH_SET_TEXT_INVISIBLE_ALERT: "//div[@id='set-text-invisible-alert']//div",
    XPATH_SET_TEXT_INVISIBLE_BUTTON_ALERT: "//button[contains(text(),'Set text with invisible Alert')]",
    XPATH_SHOW_TEXT_INVISIBLE_BUTTON_ALERT: "//button[contains(text(),'Show text invisible alert')]",
    XPATH_SET_TYPE_INVISIBLE_ALERT: "//div[@id='set-type-invisible-alert']//div",
    XPATH_SET_TYPE_INVISIBLE_BUTTON_ALERT: "//button[contains(text(),'Set success type for invisible Alert')]",
    XPATH_SHOW_TYPE_INVISIBLE_BUTTON_ALERT: "//button[contains(text(),'Show type invisible alert')]",
    XPATH_SET_TYPE_ALERT: "//div[@id='set-type-alert']//div",
    XPATH_SET_TYPE_BUTTON_ALERT: "//button[contains(text(),'Set success type for Alert')]",
    XPATH_SET_TYPE_ERROR_BUTTON_ALERT: "//button[contains(text(),'Set error type for Alert')]",
    XPATH_SET_XSS_VALUE_ALERT: "//div[@id='set-text-xss-alert']//div",
    XPATH_SET_XSS_VALUE_BUTTON_ALERT: "//button[contains(text(),'Set text XSS value for Alert')]",
    XPATH_SET_TEXT_NO_PARAM_ALERT: "//div[@id='set-text-no-param-alert']//div",
    XPATH_SET_TEXT_NO_PARAM_BUTTON_ALERT: "//button[contains(text(),'Set text with no parameter for Alert')]",
    XPATH_ONLY_TEXT_ALERT: "//div[@id='only-text-alert']//div",
    XPATH_ONLY_TYPE_ERROR_ALERT: "//div[@id='only-type-error-alert']//div",
    XPATH_ONLY_TYPE_SUCCESS_ALERT: "//div[@id='only-type-success-alert']//div",
    XPATH_ONLY_DISABLED_TRUE_ALERT: "//div[@id='only-disabled-true-alert']//div",
    XPATH_ONLY_DISABLED_FALSE_ALERT: "//div[@id='only-disabled-false-alert']//div",
    XPATH_ONLY_VISIBLE_ALERT: "//div[@id='only-Visible-alert']//div",
    XPATH_ONLY_INVISIBLE_ALERT: "//div[@id='only-Invisible-alert']//div",
    XPATH_NO_OPTION_ALERT: "//div[@id='nooption-alert']//div"
};