module.exports = {
    XPATH_BODY: "//body",
    XPATH_UI_CHECKBOX: "//div[@id='checkUIcheckbox-id']",
    XPATH_GET_NEW_ADDED_ITEM_BTN: "//button[contains(text(),'Get New Added Item For Checkbox Button')]",
    XPATH_CHECKBOX_FULL_OPTION: "//div[@id='CFO_M_checkbox_ID']",
    XPATH_WITHOUT_OPTION_VALUE: "//div[@id='CWOV_M_checkbox_ID']",
    XPATH_ONLY_OPTION_VALUE: "//div[@id='CWOV_M_checkbox_ID']",
    XPATH_GET_NEW_ADDED_ITEM_INVISIBLE_BTN: "//button[contains(text(),'Get New Added Item For Invisible Chkbox Button')]",
    XPATH_GET_NEW_ADDED_ITEM_ONLY_VALUE_BTN: "//button[contains(text(),'Get New Added Item With Only Value Checkbox Button')]",
    XPATH_GET_ITEM_INDEX_BTN: "//button[contains(text(),'Get Item Index For Checkbox Button')]",
    XPATH_GET_ITEMS_FOR_MULTIPLECHOICE_BTN: "//button[contains(text(),'Get Items For Checkbox Button')]",
    XPATH_GET_VALUE_SELECTED_ITEM: "//div[@id='GV_checkbox_ID']//span[@class='kuc-input-checkbox-item' and ./label/text()='GV_Default_Item_Checkbox']//label",
    XPATH_GET_VALUE_BTN: "//button[contains(text(),'Get Value For Checkbox Button')]",
    XPATH_SET_VALUE_DROPDOWN: "//div[@id='SV_checkbox_ID']//span[@class='kuc-input-checkbox-item' and ./label/text()='SV_Default_Item_Checkbox' and ./input/@disabled]//label",
    XPATH_ITEM_ENABLED_CONTENT: "//div[@id='SDI_checkbox_ID']//span[@class='kuc-input-checkbox-item' and ./label/text()='SDI_Default_Item_Checkbox' and ./input/@disabled]//label",
    XPATH_ENABLE_ITEM_ENABLED_CONTENT: "//div[@id='SEI_checkbox_ID']//span[@class='kuc-input-checkbox-item' and ./label/text()='SEI_Default_Item_Checkbox' and ./input/@disabled]//input[@disabled]",
    XPATH_ENABLE_ITEM_DISABLED_CONTENT: "//div[@id='SEI_checkbox_ID']//span[@class='kuc-input-checkbox-item' and ./label/text()='SEI_Item_Checkbox_Disable' and ./input/@disabled]//input[@disabled]",
    XPATH_SHOW_DROPDOWN: "//div[@id='show_checkbox_ID']",
    XPATH_HIDE_DROPDOWN: "//div[@id='hide_checkbox_ID']",
    XPATH_DISABLE_DROPDOWN: "//div[@id='disable_checkbox_ID']//span[@class='kuc-input-checkbox-item' and ./label/text()='disable_Default_Item_Checkbox' and ./input/@disabled]//label",
    XPATH_ENABLE_DROPDOWN: "//div[@id='enable_checkbox_ID']//span[@class='kuc-input-checkbox-item' and ./label/text()='enable_Default_Item_Checkbox' and ./input/@disabled]//input[@disabled]",
    XPATH_ITEM_ON_CHANGE_FUNC: "//label[contains(text(),'on_function_Item_Checkbox_1')]",
    XPATH_ITEM_ON_CHANGE_TRIG: "//label[contains(text(),'on_trigger_Item_Checkbox_1')]"
};