module.exports = {
    XPATH_BODY: "//body",
    XPATH_OPERATION_CONTENT: {
        "item_1": "//span[@class='kuc-list-item-label'][contains(text(),'ONDC_Item_Dropdown_1')]",
        "item_2": "//span[@class='kuc-list-item-label'][contains(text(),'ONDC_Item_Dropdown_2')]"
    },
    XPATH_BLANK_SELECTED: "//div[@id='ONSDB_ID']//div[@class='kuc-dropdown-selected']/span/span",
    XPATH_DEFAULT_SELECTED: "//div[@id='ODSD_ID']//div[@class='kuc-dropdown-selected']/span/span[1]",
    XPATH_DROPDOWN_CLICK: "//div[@id='OCAD_ID']//div[@class='kuc-dropdown-selected']",
    XPATH_CONTENT_AREA: "//div[@id='OCAD_ID']//div[@class='kuc-list-outer'][@style='display: block']",
    XPATH_GET_PREDEFINED_ITEMS_BUTTON: "//button[@class='kuc-btn normal'][contains(text(), 'Get Predefined Items Button')]",
    XPATH_CONTENT_AREA_PREDEFINED: "//div[@id='OCDI_ID']//div[@class='kuc-list-outer'][@style='display: block']",
    XPATH_PREDEFINED_DROPDOWN: "//div[@id='OCDI_ID']//span[@class='kuc-dropdown-selected-name']/parent::div",
    XPATH_DISPLAYED_ITEMS_PREDEFINED: {
        "item_1": "(//div[@id='OCDI_ID']//span[@class='kuc-list-item-label'])[1]",
        "item_2": "(//div[@id='OCDI_ID']//span[@class='kuc-list-item-label'])[2]"
    },
    XPATH_ITEM_TO_BE_SELECTED: "//div[@id='OCDI_ID']//div[@class='kuc-list-outer']//span[contains(text(),'OCDI_Item_Dropdown_2')]",
    XPATH_ITEM_AFTER_SELECTED: "//div[@id='OCDI_ID']//div[@class='kuc-list-item kuc-list-item-selected']",
    XPATH_ITEM_AFTER_SELECTED_GET_COLOR: "//div[@id='OCDI_ID']//div[@class='kuc-list-item kuc-list-item-selected']//span[@class='kuc-list-item-label']",

    XPATH_CLICK_OUTSIDE_DROPDOWN: "//div[@id='OCAI_ID']//span[@class='kuc-dropdown-selected-name']/parent::div",
    XPATH_CLICK_OUTSIDE_DROPDOWN_SELECTED_VALUE: "//div[@id='OCAI_ID']//span[@class='kuc-dropdown-selected-name']",
    XPATH_OUTSIDE_AREA: "//div[@class='contents-bottommenu-gaia']//div[@class='gaia-argoui-app-index-pager']",
    XPATH_DROPDOWN_CONTENT: "//div[@id='OCAI_ID']//div[@class='kuc-list-outer'][@style='display: block']",
    XPATH_SELECT_ITEM: "//span[contains(text(),'OCAI_Item_Dropdown_2')]",
    XPATH_DISABLED_ITEM: "//div[@id='CWOV_ID']//span[@class='kuc-list-item-label'][contains(text(),'OCAI_Default_Item_Dropdown')]/parent::div[@class='kuc-list-item kuc-list-item-selected kuc-list-item-disable']",
    XPATH_CONS_DEFAULT_VALUE: "//span[@class='kuc-dropdown-selected-name']//span[contains(text(),'OCAI_Default_Item_Dropdown')]",
    XPATH_GET_NEW_ADDED_ITEM_BTN: "//button[contains(text(),'Get New Added Item Button')]",
    XPATH_DROPDOWN_FULL_OPTION: "//div[@id='CFO_ID']",
    XPATH_WITHOUT_OPTION_VALUE: "//div[@id='CWOV_ID']",
    XPATH_GET_NEW_ADDED_ITEM_INVISIBLE_BTN: "//button[contains(text(),'Get New Added Item For Invisible Dropdown Button')]",
    XPATH_GET_NEW_ADDED_ITEM_ONLY_VALUE_BTN: "//button[contains(text(),'Get New Added Item With Only Value Dropdown Button')]",
    XPATH_VERIFY_NEW_ADDED_ITEM: "//button[contains(text(),'Verify The Added Item Button')]",
    XPATH_VERIFY_NEW_ADDED_ITEM_WITH_DISABLED_ATTR: "//button[contains(text(),'Verify The Added Item Disabled Default Button')]",
    XPATH_REMOVE_ITEM_DROPDOWN: "//div[@id='RI_ID']//div[@class='kuc-dropdown-selected']",
    XPATH_ITEM_TO_REMOVE: "//span[@class='kuc-list-item-label'][contains(text(),'RI_Default_Item_Dropdown')]",
    XPATH_ITEM_TO_SELECT: "//span[contains(text(),'RI_Item_Dropdown_2')]",
    XPATH_GET_ITEMS_FOR_DROPDOWN_BTN: "//button[contains(text(),'Get Items For Dropdown Button')]",
    XPATH_GET_VALUE_DROPDOWN: "//div[@id='GV_ID']//div[@class='kuc-dropdown-selected']//span[@class='kuc-dropdown-selected-name']",
    XPATH_GET_VALUE_SELECTED_ITEM: "//div[@class='kuc-list-item kuc-list-item-selected kuc-list-item-disable']//span[@class='kuc-list-item-label'][contains(text(),'GV_Default_Item_Dropdown')]",
    XPATH_GET_VALUE_BTN: "//button[contains(text(),'Get Value For Dropdown Button')]",
    XPATH_SET_VALUE_DROPDOWN: "//div[@id='SV_ID']//div[@class='kuc-dropdown-selected']",
    XPATH_SET_VALUE_DROPDOWN_BUTTON: "//button[contains(text(),'Set Value of Dropdown')]",
    XPATH_SET_DISABLED_VALUE_DROPDOWN_BUTTON: "//button[contains(text(),'Set Disabled Value of Dropdown')]",
    XPATH_SET_BLANK_VALUE_DROPDOWN_BUTTON: "//button[contains(text(),'Set Blank Value of Dropdown')]",
    XPATH_DISABLE_ITEM_DROPDOWN: "//span[@class='kuc-dropdown-selected-name']//span[contains(text(),'SDI_Default_Item_Dropdown')]",
    XPATH_DISABLE_BUTTON_DROPDOWN: "//div[@id='SDI_ID']/following-sibling::button[contains(text(), 'Disable Dropdown')]",
    XPATH_ITEM_ENABLED_CONTENT: "//span[contains(text(),'SDI_Default_Item_Dropdown')]/parent::div[contains(@class, 'kuc-list-item')]",
    XPATH_ITEM_DISABLED_CONTENT: "//span[contains(text(),'SDI_Item_Dropdown_Disable')]/parent::div[contains(@class, 'kuc-list-item')]",
    XPATH_ENABLE_ITEM_DROPDOWN: "//span[@class='kuc-dropdown-selected-name']//span[contains(text(),'SEI_Default_Item_Dropdown')]",
    XPATH_ENABLE_ITEM_ENABLED_CONTENT: "//span[contains(text(),'SEI_Default_Item_Dropdown')]/parent::div[@disabled]",
    XPATH_ENABLE_ITEM_DISABLED_CONTENT: "//span[contains(text(),'SEI_Item_Dropdown_Disable')]/parent::div[@disabled]",
    XPATH_SHOW_DROPDOWN: "//div[@id='show_ID']",
    XPATH_HIDE_DROPDOWN: "//div[@id='hide_ID']",
    XPATH_DISABLE_DROPDOWN: "//div[@class='kuc-dropdown kuc-dropdown-disable']/ancestor::div[@id='disable_ID']",
    XPATH_ENABLE_DROPDOWN: "//div[@class='kuc-dropdown kuc-dropdown-disable']/ancestor::div[@id='enable_ID']",
    XPATH_ON_FUNC_DROPDOWN: "//div[@id='on_function_ID']//span[@class='kuc-dropdown-selected-name']",
    XPATH_ITEM_ON_CHANGE_FUNC: "//span[contains(text(),'on_function_Item_Dropdown_1')]",
    XPATH_ON_TRIGGER_DROPDOWN: "//div[@id='on_trigger_ID']//span[@class='kuc-dropdown-selected-name']",
    XPATH_ITEM_ON_CHANGE_TRIG: "//span[contains(text(),'on_trigger_Item_Dropdown_1')]",
    XPATH_UI_DROPDOWN: "//div[@id='check-UI-dropdown-id']//span[@class='kuc-dropdown-selected-name']",
    XPATH_UI_CLICK_DROPDOWN: "//div[@id='check-UI-dropdown-id']//div[@class='kuc-dropdown-selected']",
    XPATH_UI_DROPDOWN_OUTER: "//div[@id='check-UI-dropdown-id']//div[@class='kuc-list-outer']",
    XPATH_UI_DROPDOWN_GET_STATE_BTN: "//button[contains(text(),'Get State Of UI Items Button')]",
    XPATH_UI_NOTE_HAVE_ITEM_DROPDOWN_GET_STATE_BTN: "//button[contains(text(),'Get State Of UI Not Have Items Button')]",
    XPATH_UI_HOVER_DROPDOWN_BTN :"//div[@id='check-hover-dropdown-id']//div[@class='kuc-dropdown']",
    XPATH_UI_HOVER_DROPDOWN_ITEM :  "//div[@id='check-hover-dropdown-id']//div[@class='kuc-list-outer']//div[@class='kuc-list-item']"
};