module.exports = {
     XPATH_BODY: "//body",
     XPATH_UI: "//span[contains(text(), 'UILabel')]",
     // XPATH_CONSTRUCTOR: "//span[contains(text(), 'constructorLabel')]",
     XPATH_FULL_OPTION_LABEL: "//div[@id='full-option-label']//div[@class='kuc-label']",
     XPATH_SET_TEXT_LABEL: "//div[@id='set-text-label']//span",
     XPATH_SET_TEXT_BUTTON_LABEL: "//button[contains(text(),'Set text for label not contain existing text')]",
     XPATH_SET_TEXT_BUTTON_1_LABEL: "//button[contains(text(),'Set text for label contain existing text')]",
     XPATH_SET_REQUIRED: "//span[contains(text(), 'setRequiredTrueLabel')]",
     XPATH_SET_REQUIRED_ATTERISK: "//span[contains(text(), 'setRequiredTrueLabel')]/parent::div/span[contains(text(), '*')]",
     XPATH_SET_REQUIRED_TRUE_FOR_REQUIRED_LABEL: "//span[contains(text(), 'setRequiredTrueToRequiredLabel')]",
     XPATH_SET_REQUIRED_TRUE_FOR_REQUIRED_ATTERISK: "//span[contains(text(), 'setRequiredTrueToRequiredLabel')]/parent::div/span[contains(text(), '*')]",
     XPATH_SET_REQUIRED_FALSE_FOR_REQUIRED_LABEL: "//span[contains(text(), 'setRequiredFalseLabel')]",
     XPATH_SET_REQUIRED_FALSE_FOR_REQUIRED_ATTERISK: "//span[contains(text(), 'setRequiredFalseLabel')]/parent::div/span[contains(text(), '*')]",
     XPATH_SET_FALSE_REQUIRED_LABEL: "//div[@id='set-false-required-label']//span[@class='kuc-require']",
     XPATH_SET_FALSE_REQUIRED_BUTTON_LABEL: "//button[contains(text(),'Set False for the current required Label')]",
     XPATH_SET_TRUE_REQUIRED_LABEL: "//div[@id='set-true-required-label']//span[@class='kuc-require']",
     XPATH_SET_TRUE_REQUIRED_BUTTON_LABEL: "//button[contains(text(),'Set True for the current unrequired Label')]",
     XPATH_VISIBLE_SHOW_LABEL: "//div[@id='show-visible-label']//span",
     XPATH_INVISIBLE_SHOW_LABEL: "//div[@id='show-invisible-label']//span",
     XPATH_SHOW_BUTTON_LABEL: "//button[contains(text(),'Show Label')]",
     XPATH_VISIBLE_HIDE_LABEL: "//div[@id='hide-visible-label']//span",
     XPATH_INVISIBLE_HIDE_LABEL: "//div[@id='hide-invisible-label']//span",
     XPATH_HIDE_BUTTON_LABEL: "//button[contains(text(), 'Hide Label')]",
     XPATH_DISABLE_ENABLE_LABEL: "//div[@id='disable-enable-label']//div[@class='kuc-label']",
     XPATH_DISABLE_DISABLE_LABEL: "//div[@id='disable-disable-label']//div[@class='kuc-label']",
     XPATH_DISABLE_BUTTON_LABEL: "//button[contains(text(), 'Disable Label')]",
     XPATH_ENABLE_ENABLE_LABEL: "//div[@id='enable-enable-label']//div[@class='kuc-label']",
     XPATH_ENABLE_DISABLE_LABEL: "//div[@id='enable-disable-label']//div[@class='kuc-label']",
     XPATH_ENABLE_BUTTON_LABEL: "//button[contains(text(), 'Enable Label')]",
     // XPATH_ENABLE: "//span[contains(text(), 'enableLabel')]",
     XPATH_ON_FUNC: "//span[contains(text(), 'onFunctionLabel')]",
     XPATH_ON_TRIG: "//span[contains(text(), 'onTriggerLabel')]",
     XPATH_NO_OPTION_LABEL: "//div[@id='no-option-label']//div[@class='kuc-label']",
     XPATH_ONLY_TEXT_LABEL: "//span[contains(text(),'only options.Text Label')]",
     XPATH_ONLY_REQUIRED_LABEL: "//div[@id='only-isRequired-label-true']//span[@class='kuc-require']",
     XPATH_ONLY_REQUIRED_LABEL_1: "//div[@id='only-isRequired-label-false']//span[@class='kuc-require']",
     XPATH_ONLY_DISABLED_BUTTON: "//button[contains(text(),'Get Value of isDisabled true')]",
     XPATH_ONLY_DISABLED_BUTTON_1: "//button[contains(text(),'Get Value of isDisabled false')]",
     XPATH_ONLY_VISIBLE_LABEL: "//div[@id='only-isVisibled-label-true']",
     XPATH_ONLY_VISIBLE_LABEL_1: "//div[@id='only-isVisibled-label-false']",
     XPATH_SET_XSS_VALUE_LABEL: "//div[@id='set-XSS-value-label']//div[@class='kuc-label']",
     XPATH_SET_XSS_BUTTON_LABEL: "//button[contains(text(),'Set text with XSS value')]",
     XPATH_SET_TEXT_INVISIBLE_LABEL: "//div[@id='set-text-invisible-label']//div[@class='kuc-label']",
     XPATH_SET_TEXT_INVISIBLE_BUTTON_LABEL: "//button[contains(text(),'Set text with invisible Label')]",
     XPATH_SHOW_TEXT_INVISIBLE_BUTTON_LABEL: "//button[contains(text(),'Show text invisible')]",
     XPATH_SET_TEXT_BLANK_LABEL: "//div[@id='set-text-blank-label']//div[@class='kuc-label']",
     XPATH_SET_TEXT_BLANK_BUTTON_LABEL: "//button[contains(text(),'Set text to blank')]",
     XPATH_SET_TEXT_NO_PARAM_LABEL: "//div[@id='set-text-no-param-label']//div[@class='kuc-label']",
     XPATH_SET_TEXT_NO_PARAM_BUTTON_LABEL: "//button[contains(text(),'Set text with no parameter for Label')]",
     XPATH_SET_REQUIRED_INVISIBLE_LABEL: "//div[@id='set-required-invisible-label']//span[@class='kuc-require']",
     XPATH_SET_REQUIRED_BUTTON_INVISIBLE_LABEL: "//button[contains(text(),'Set required for invisible label')]",
     XPATH_SET_REQUIRED_NO_PARAM_LABEL: "//div[@id='set-required-no-param-label']//span[@class='kuc-require']",
     XPATH_SET_REQUIRED_NO_PARAM_BUTTON_LABEL: "//button[contains(text(),'Set required without parameter for label')]",
   
};