module.exports = {
     XPATH_BODY: "//body",
     XPATH_GET_NEW_ADDED_ITEM_BTN: "//button[contains(text(),'Get New Added Item MulChoice Button')]",
     XPATH_MULCHOICE_FULL_OPTION: "//div[@id='CFO_M_MulChoice_ID']",
     XPATH_WITHOUT_OPTION_VALUE: "//div[@id='CWOV_M_MulChoice_ID']",
     XPATH_ONLY_OPTION_VALUE: "//div[@id='CWOV_M_MulChoice_ID']",
     XPATH_GET_NEW_ADDED_ITEM_INVISIBLE_BTN: "//button[contains(text(),'Get New Added Item For Invisible MulChoice Button')]",
     XPATH_GET_NEW_ADDED_ITEM_ONLY_VALUE_BTN: "//button[contains(text(),'Get New Added Item With Only Value MulChoice Button')]",
     XPATH_GET_NEW_ADDED_ITEM_WITHOUT_VALUE_BTN: "//button[contains(text(),'Get New Added Item Without Value MulChoice Button')]",
     XPATH_GET_VALUE_OF_REMOVED_ITEMS_MULCHOICE_BTN: "//button[contains(text(),'Get Items of Removed MulChoice Button')]",
     XPATH_GET_ITEM_INDEX_BTN: "//button[contains(text(),'Get Item Index For MultipleChoice Button')]",
     XPATH_GET_ITEMS_FOR_MULTIPLECHOICE_BTN: "//button[contains(text(),'Get Items For MultipleChoice Button')]",
     XPATH_GET_VALUE_SELECTED_ITEM: "//div[@class='kuc-list-item kuc-list-item-selected']//span[contains(text(),'GV_Default_MulChoice_Item')]",
     XPATH_GET_VALUE_BTN: "//button[contains(text(),'Get Value For MultipleChoice Button')]",
     XPATH_SET_VALUE_DROPDOWN: "//span[contains(text(),'SV_Default_MulChoice_Item')]",
     XPATH_ITEM_ENABLED_CONTENT: "//span[contains(text(),'SDI_Default_MulChoice_Item')]/parent::div[contains(@class, 'kuc-list-item-disable')]",
     XPATH_ENABLE_ITEM_ENABLED_CONTENT: "//span[contains(text(),'SEI_Default_MulChoice_Item')]/parent::div[@disabled]",
     XPATH_ENABLE_ITEM_DISABLED_CONTENT: "//span[contains(text(),'SEI_MulChoice_Item_Disable')]/parent::div[@disabled]",
     XPATH_SHOW_DROPDOWN: "//div[@id='show_MulChoice_ID']",
     XPATH_HIDE_DROPDOWN: "//div[@id='hide_MulChoice_ID']",
     XPATH_DISABLE_DROPDOWN: "//div[@id='disable_MulChoice_ID']/div[@class='kuc-list-item kuc-list-item-selected kuc-list-item-disable']",
     XPATH_ENABLE_DROPDOWN: "//div[@id='enable_MulChoice_ID']/div[@class='kuc-multiple-list kuc-list-outer  kuc-multiple-list-disable']",
     XPATH_ITEM_ON_CHANGE_FUNC: "//span[contains(text(),'on_function_MulChoice_Item_1')]",
     XPATH_ITEM_ON_CHANGE_TRIG: "//span[contains(text(),'on_trigger_MulChoice_Item_1')]"
};