module.exports = {
     XPATH_BODY: "//body",
     // XPATH_TXT_UI: "div[@id='constructor-text]'//input[@value= 'uiText']",
     XPATH_CONSTRUCTOR_TEXT: "//div[@id='constructor-text']//input[@class='kuc-input-text']",
     // XPATH_TXT_FULL_CONSTRUCTOR: "//input[@value= 'fullConstructorText']",
     XPATH_SET_VALUE_TEXT: "//div[@id='set-value-text']//input[@class='kuc-input-text']",
     XPATH_SET_VALUE_BUTTON_TEXT: "//button[contains(text(),'Set Value of Text with string')]",
     XPATH_SET_VALUE_BUTTON_1_TEXT: "//button[contains(text(),'Set Value of Text without string')]",
     XPATH_SHOW_INVISIBLE_TEXT: "//div[@id='show-invisible-text']//input[@class='kuc-input-text']",
     XPATH_SHOW_VISIBLE_TEXT: "//div[@id='show-visible-text']//input[@class='kuc-input-text']",
     XPATH_SHOW_BUTTON_TEXT: "//button[contains(text(),'Show Text')]",
     XPATH_HIDE_VISIBLE_TEXT: "//div[@id='hide-visible-text']//input[@class='kuc-input-text']",
     XPATH_HIDE_INVISIBLE_TEXT: "//div[@id='hide-invisible-text']//input[@class='kuc-input-text']",
     XPATH_HIDE_BUTTON_TEXT: "//button[contains(text(),'Hide Text')]",
     XPATH_DISABLE_ENABLED_TEXT: "//div[@id='disable-enabled-text']//input[@class='kuc-input-text']",
     XPATH_DISABLE_DISABLED_TEXT: "//div[@id='disable-enabled-text']//input[@class='kuc-input-text']",
     XPATH_DISABLE_BUTTON_TEXT: "//button[contains(text(),'Disable Text')]",
     XPATH_ENABLE_DISABLED_TEXT: "//div[@id='enable-disabled-text']input[@class='kuc-input-text']",
     XPATH_ENABLE_ENABLED_TEXT: "//div[@id='enable-enabled-text']input[@class='kuc-input-text']",
     XPATH_ENABLE_BUTTON_TEXT: "//button[contains(text(),'Enable Text')]",
     XPATH_ON_CHANGE_FUNCTION_TEXT: "//input[@value= 'onChangeFunctionText']",
     XPATH_ON_CHANGE_TRIGGER_TEXT: "//input[@value= 'onChangeTriggerText']",
     XPATH_ON_CLICK_FUNCTION_TEXT: "//input[@value= 'onClickFunctionText']",
     XPATH_ON_CLICK_TRIGER_TEXT: "//input[@value= 'onClickTriggerText']",
};